### ISSUE TITLE
Use -N in wget

### ISSUE THREAD

**Issue by schnumsel** [mittwald/magento-cronjobs#3]
Hello,

I was trying to build a magento-deployment for your mittwaldservers. 
If I use the command given in your README.md, cron.sh.1 is saved, the original magento cron is left in place and your servers turn wild :)
Please change to:

`wget -N https://raw.githubusercontent.com/mittwald/magento-cronjobs/master/cron.sh`

as this will overwrite the original code.

Best regards,

Willi

**Comment by pstranghoener** [comment]
Hey Willi, 

thanks for the change, but we dont want that the original code is overwritten. If you do an update its overwritten again and you have to change it again.

Best Regards Philipp

**Comment by schnumsel** [comment]
Never mind, I know now, what I am doing, but using your code on an upgrade just killed one of your servers, so I thougt it would be better that way.
Of course you can also install the cronjob using cron.sh.1 :(

**Comment by pstranghoener** [comment]
His Script is only for our Customers on Mittwald Server.
