### ISSUE TITLE
Viele Magento 2 Cronjobs werden auf Mittwald nicht ausgeführt

### ISSUE THREAD

**Issue by a-fellerer** [mittwald/magento-cronjobs#4]
In einem Magento 2 Cron Scheduler kann ich sehen, dass viele Cronjobs nicht ausgeführt werden.

Welche Empfehlungen hab ihr für die Einstellungen in Shops -> Konfiguration -> Erweitert -> System -> Cron (geplante Tasks)?

Die Betroffene Installation ist ******* 

// edit - removed account

**Comment by twiesing** [comment]
Hallo!

Am besten wäre es, wenn du dich mit dem Anliegen einmal an unsere Kollegen vom Support wendest.

Die Kontaktdaten findest du hier: https://www.mittwald.de/kontakt-support

Viele Grüße
Tobias
